# Alexey Savostin
# email: alexey.savostin@gmail.com
# 06.2024

version: "3"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - iot
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD_FILE=/run/secrets/influxdb_password
      - DOCKER_INFLUXDB_INIT_ORG=Institute
      - DOCKER_INFLUXDB_INIT_BUCKET=main_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=/run/secrets/influxdb_token
    secrets:
      - influxdb_password
      - influxdb_token
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      - iot
    secrets:
      - influxdb_token
      - mqtt_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - iot
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_password
    secrets:
      - grafana_password
      - influxdb_token
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  iot:

volumes:
  grafana-data:
  influxdb-data:
  influxdb-config:

secrets:
  influxdb_password:
    file: ./secrets/influxdb_password.txt
  influxdb_token:
    file: ./secrets/influxdb_token.txt
  grafana_password:
    file: ./secrets/grafana_password.txt
  mqtt_password:
    file: ./secrets/mqtt_password.txt
