{
 "title": "WISE-2410",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "sensor",
    "label": "Sensor ID",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"main_data\", tag: \"tag\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "sensor",
   "collapsed": true,
   "panels": [
    {
     "title": "Device Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Device_Events\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value\n    }))\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Power Source",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Device_PowerSrc\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value\n    }))\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Battary Volt",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Device_BatteryVolt\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({\n    _time: r._time,\n    _value: r._value / 1000.0,\n  }))\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uplink\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"freq\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "FCNT",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uplink\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fcnt\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "FCNT",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uplink\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fcnt\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({\n    _time: r._time,\n    _value: r._value,\n    _field: if r._field == \"fcnt\" then \"FCNT\" else \"Loss\"\n  }))\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uplink\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"packet_loss\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      _field: if r._field == \"packet_loss\" then \"Loss\" else \"FCNT\"\n  }))\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "LSNR",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uplink\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lsnr\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "LSNR",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 9, "x": 15, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "dbm" } },
     "targets": [
      {
       "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uplink\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lsnr\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "RSSI",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uplink\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "RSSI",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 9, "x": 15, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uplink\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Sensor Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TempHumi_Status\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Alarm Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TempHumi_Event\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TempHumi_SenVal\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({\n    _time: r._time,\n    _value: r._value / 1000.0,\n    _field: if r._field == \"TempHumi_SenVal\" then \"Temperature\" \n    else \"\"\n  }))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TempHumi_SenVal\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({\n    _time: r._time,\n    _value: r._value / 1000.0,\n    _field: if r._field == \"TempHumi_SenVal\" then \"Temperature\" \n    else \"\"\n  }))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperature Event",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TempHumi_Event\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Accelerometer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "X-Axis Alarm Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Accelerometer_X-Axis_SenEvent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Y-Axis Alarm Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Accelerometer_Y-Axis_SenEvent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Z-Axis Alarm Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Accelerometer_Z-Axis_SenEvent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Alarm History",
   "type": "state-timeline",
   "description": "High Alarm Status of Velocity RMS",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Accelerometer_X-Axis_SenEvent\" or r[\"_field\"] == \"Accelerometer_Y-Axis_SenEvent\" or r[\"_field\"] == \"Accelerometer_Z-Axis_SenEvent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      _field: if r._field == \"Accelerometer_X-Axis_SenEvent\" then \"X-Axis High Alarm\" \n      else if r._field == \"Accelerometer_Y-Axis_SenEvent\" then \"Y-Axis High Alarm\" \n      else \"Z-Axis High Alarm\"\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Velocity RMS",
   "type": "timeseries",
   "description": "OA Value of Vibration Velocity обозначает интегральное значение или общий уровень вибрации, который суммирует вклад всех частот вибрации в пределах определенного диапазона. Это усредненное значение, которое представляет общую вибрационную активность оборудования.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mm/s" } },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Accelerometer_X-Axis_OAVelocity\" \n  or r[\"_field\"] == \"Accelerometer_Y-Axis_OAVelocity\" \n  or r[\"_field\"] == \"Accelerometer_Z-Axis_OAVelocity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value / 100.0,\n      _field: if r._field == \"Accelerometer_X-Axis_OAVelocity\" then \"X-Axis OAVelocity\" \n      else if r._field == \"Accelerometer_Y-Axis_OAVelocity\" then \"Y-Axis OAVelocity\" \n      else \"Z-Axis OAVelocity\"\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Acceleration Peak",
   "type": "timeseries",
   "description": "Peak Value of Acceleratin обозначает наибольшее значение виброускорения, зарегистрированное в течение определенного периода времени. Это наибольшая амплитуда вибрации в данной временной точке.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Accelerometer_X-Axis_Peakmg\" or r[\"_field\"] == \"Accelerometer_Y-Axis_Peakmg\" \n  or r[\"_field\"] == \"Accelerometer_Z-Axis_Peakmg\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value / 1000.0,\n      _field: if r._field == \"Accelerometer_X-Axis_Peakmg\" then \"X-Axis Acceleration Peak\" \n      else if r._field == \"Accelerometer_Y-Axis_Peakmg\" then \"Y-Axis Acceleration Peak\" \n      else \"Z-Axis Acceleration Peak\"\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Acceleration RMS",
   "type": "timeseries",
   "description": "RMS of Acceleration - среднеквадратичное значение виброускорения используются для получения более стабильных и представительных показателей вибрационной активности. В отличие от пиковых значений, которые могут быть вызваны кратковременными аномалиями, RMS учитывает все измерения за период времени, что делает его более устойчивым к случайным колебаниям.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Accelerometer_X-Axis_RMSmg\" or r[\"_field\"] == \"Accelerometer_Y-Axis_RMSmg\" or r[\"_field\"] == \"Accelerometer_Z-Axis_RMSmg\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value / 1000.0,\n      _field: if r._field == \"Accelerometer_X-Axis_RMSmg\" then \"X-Axis Acceleration RMS\" \n      else if r._field == \"Accelerometer_Y-Axis_RMSmg\" then \"Y-Axis Acceleration RMS \" \n      else \"Z-Axis Acceleration RMS\"\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Accelerometer statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Peak-to-Peak Displacement",
   "type": "timeseries",
   "description": "Peak-to-Peak Displacement - это разница между наибольшим положительным и наибольшим отрицательным отклонением вибрационного сигнала. Этот параметр измеряет полный диапазон движения объекта за один цикл колебания. Он выражается в единицах длины, таких как микрометры (µm).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "micrometr" } },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Accelerometer_X-Axis_Peak-to-Peak_Displacement\" \n  or r[\"_field\"] == \"Accelerometer_Y-Axis_Peak-to-Peak_Displacement\" \n  or r[\"_field\"] == \"Accelerometer_Z-Axis_Peak-to-Peak_Displacement\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value / 100.0,\n      _field: if r._field == \"Accelerometer_X-Axis_Peak-to-Peak_Displacement\" then \"X-Axis Peak-to-Peak Displacement\" \n      else if r._field == \"Accelerometer_Y-Axis_Peak-to-Peak_Displacement\" then \"Y-Axis Peak-to-Peak Displacement\" \n      else \"Z-Axis Peak-to-Peak Displacement\"\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Kurtosis",
   "type": "stat",
   "description": "Kurtosis - это мера \"остроты\" или \"пикообразности\" распределения данных. Он показывает, насколько сильно распределение отличается от нормального распределения в терминах высоты и тяжёлых хвостов.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Accelerometer_X-Axis_Kurtosis\" \n  or r[\"_field\"] == \"Accelerometer_Y-Axis_Kurtosis\" \n  or r[\"_field\"] == \"Accelerometer_Z-Axis_Kurtosis\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value / 100.0,\n      _field: if r._field == \"Accelerometer_X-Axis_Kurtosis\" then \"X-Axis Kurtosis\" \n      else if r._field == \"Accelerometer_Y-Axis_Kurtosis\" then \"Y-Axis Kurtosis\" \n      else \"Z-Axis Kurtosis\"\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Skewness - ",
   "type": "stat",
   "description": "Skewness - это статистический показатель, который описывает асимметрию распределения данных относительно его среднего значения. В контексте вибрационного анализа и мониторинга состояния оборудования, смещённость помогает выявлять отклонения в вибрационном сигнале, что может свидетельствовать о механических проблемах.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Accelerometer_X-Axis_Skewness\" \n  or r[\"_field\"] == \"Accelerometer_Y-Axis_Skewness\" \n  or r[\"_field\"] == \"Accelerometer_Z-Axis_Skewness\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value / 100.0,\n      _field: if r._field == \"Accelerometer_X-Axis_Skewness\" then \"X-Axis Skewness\" \n      else if r._field == \"Accelerometer_Y-Axis_Skewness\" then \"Y-Axis Skewness\" \n      else \"Z-Axis Skewness\"\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Crest Factor",
   "type": "stat",
   "description": "Crest Factor - это отношение максимального (пикового) значения сигнала к его среднеквадратичному (RMS) значению. Он рассчитывается по формуле:\n Crest Factor = Peak Value / RMS Value.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Accelerometer_X-Axis_CrestFactor\" \n  or r[\"_field\"] == \"Accelerometer_Y-Axis_CrestFactor\" \n  or r[\"_field\"] == \"Accelerometer_Z-Axis_CrestFactor\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value / 100.0,\n      _field: if r._field == \"Accelerometer_X-Axis_CrestFactor\" then \"X-Axis CrestFactor\" \n      else if r._field == \"Accelerometer_Y-Axis_CrestFactor\" then \"Y-Axis CrestFactor\" \n      else \"Z-Axis CrestFactor\"\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Deviation",
   "type": "stat",
   "description": "Стандартное отклонение — это важный статистический показатель, который измеряет разброс значений вокруг среднего значения. В контексте вибрационного анализа и мониторинга состояния оборудования, стандартное отклонение помогает оценить стабильность вибрационного сигнала и выявить отклонения от нормальной работы.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "query": "from(bucket: \"main_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Advantech\")\n  |> filter(fn: (r) => r[\"tag\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Accelerometer_X-Axis_Deviation\" \n  or r[\"_field\"] == \"Accelerometer_Y-Axis_Deviation\" \n  or r[\"_field\"] == \"Accelerometer_Z-Axis_Deviation\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value / 100.0,\n      _field: if r._field == \"Accelerometer_X-Axis_Deviation\" then \"X-Axis Deviation\" \n      else if r._field == \"Accelerometer_Y-Axis_Deviation\" then \"Y-Axis Deviation\" \n      else \"Z-Axis Deviation\"\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}